# -*- coding: utf-8 -*-
"""Day 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZKYdvUbqpfm8tu2eNEu0j7qDX3Muk6D
"""

a=10
b=10

a

b

a=10

7a=10

a7a=10

a9a=20

a$b=22

a_=20

a_

import keyword
print(keyword.kwlist)

### numbers should not be at the start of the sequence
### you cannot have special characters
### in built keywords are not supported to use as variable names

a=10.6+3j

type(a)

string='''Data
science
machine learning
ai'''

type(string)

string

string="DATA SCIENCE"

string

type(string)

string[0:2]

print(string[4])

string[4:7]

string[:4]

string

string1="Data Science"
string2="Data analytics"
string3="Data Engineering"

string1.upper()

string2.lower()

print(string1.upper(),string2.lower(),string3.upper())

print(string1)
string1.islower()

print(string2)
string2.isupper()

string1.isupper()

string="Data science"
string.isalpha()

string="Datascience"
string.isalpha()

string="abc12134"
string.isalnum()

string="12223213"
string.isnumeric()

data="    "
data.isspace()

string="data science"
string

string.split()

x="Data"
x.split("a")

































