# -*- coding: utf-8 -*-
"""Day 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oj0zEt4xLZa6iBV7Gwj4ozRnnUWr68VZ
"""

d={"key":10,"key":20}

d

type(d)

d={10:[10,20,30]}

d

### which datatype doesn't have support key declaratuion

my_dict = {
    "name":"Yuga",
    "age":23,
    "location": "Banglore"
}

my_dict["location"]

my_dict

my_dict['name']

mixed_dict = {
    "name":"Yuga",
    101:[80, 85, 90],
    3.14: {"unit":"pi"},
    True:"Active"}

mixed_dict

mixed_dict[101][-1]

employee = {
    "id":1007,
    "name":"Yugandgar",
    "department":{
        "name":"Data Science",
        "location": "Banglore",
        "floor": 3
    },
    "is_active": True
}

employee['department']['location']

mixed_dict = {
    "name": "Yugandhar",
    101: [80, 85, 90],
    3.14: {"unit": "pi"},
    True: "Active"}

mixed_dict

mixed_dict[101][-1]

emplloyee = {
    "id":1007,
    "name":"Yugandhar",
    "department":{
        "name":"Data Science",
        "location": "Banglore",
        "floor": 3
    },
    "is_active": True
}

mixed_dict = {
    "name": "Yugandhar",
    101: [80, 85, 90],
    3.14: {"unit": "pi"},
    True: "Active",
    None: 0,
    (1, 2): "tuple_key",
    "details": {
        "age": 23,
        "location": "Banglore"
    },
    "scores": (95, 87, 78),
    "is_verifed": False,
    "height": 5.9
}

temp={
    "lat":33.44,
    "lon":-94.04,
    "timezone":"America/Chicago",
    "timezone_offset":-18000,
    "Current":{
        "dt":1684373773,
        "sunrise":153876356,
        "sunset":14324544,
        "temp":234.44,
        "feels_like":292.87,
        "pressure":1016,
        "humidity":89,
        "dew_point":223,
        "uvi":5,
        "clouds":0,
        "visibility":10000,
        "wind_speed":3.6,
        "wind_deg":300,
        "weather":[
            {
                "id":800,
                "main":"Clear",
                "description":"clear sky",
                "icon":"01n"
            }
        ]
    }
    }

temp

temp['Current']['weather'][0]['icon']

temp

temp['Current']['weather'][0]['main'].upper()

temp['Current']['wind_speed']

temp

d = {
    "name":"Yugandhar",
    "age":23,
    "location": "Banglore"
}

d

d.values()

temp.values()

d.keys()

d.items()

d

temp

d.get("age")

d['name']

d

d.update({"name":"abc"})

d

d.update({"abc":"Yugandhr"})

d

d.pop("name")

d

d.update({"name":"Yugandhar"})

d

d.items

d.items()

d

d.clear()

d

del d

d

d = {
    "name":"Yugandhar",
    "age":23,
    "location": "Banglore",
}

d

d.popitem()

d

isinstance(d['age'],int)

###isinstance is used to compare the output with the datatypes

x=[1,2,3,4,5]
y=[2,3,2,3,4]
print(x)

x=[1,2,3,4,5]

x

y=(1,2,3,4)

y

y=(1,1,1,2,3,4)
y.count(1)

y=(2,3,4,5,1,1,1,2,3,4)
y.index(3)

y=(2,3,4,22,2,3,3,3)
y.index(3)

y=(0,1,2,3,4,5,6,7,8,9)
y.index(8)

y=(5,7,8,9,10,12,17)
y.index(5)

x={11,2,32,41,15,6,2,2}

x

x.add(100)

x

y=frozenset([11, 2, 3,1,2])

y

y















