# -*- coding: utf-8 -*-
"""Day 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s16X0qYVOlUftjV7vvXUUKdUpk3KnDFB
"""

x="Data"

len(x)

x="Yugandhar"

len(x)

x.upper()

x="data science"
x.find("enct")

x="Data science"
x.index("e")

x="Data science"
x.index("a")

x=" data "

len(x)

x.strip()

x.lstrip()

x.rstrip()

x="DataD"

x

x.replace("D","xyz")

x="data"
x.center(8," ")

x="20"
x.zfill(7)

x='''  data
science'''

x

x.split()

x='data \nscience'
x.splitlines()

x=['data','science']
"".join("x")

x="data"
x

### list datatype

x=[1,2.6,3+4j,"data"]

type(x)

x

x[-1]

x[2:3]

x[3:2]

x

print(x[0],type(x[0]))
print(x[1],type(x[1]))
print(x[2],type(x[2]))
print(x[3],type(x[3]))

x

x[-3]/2

x

(x[0]+x[1]/2)

x=["data","science","machine","learning",[1,2,3]]

x

x[-1]

x=[1]

x

x=['data','science',['machine','learning']]

x

x[2][-1][-3:].upper()

customers = [
    ["Ravi",["Shampo","Toothpaste"]],
    ["Anjali",["Rice","Wheat","Oil"]],
    ["Kiran", ["Biscuts", "milk"]]
]

customers[1][-1][-1]

'Biscuts'

performance = [
    ["Surat",[["Nikita",85], ["Arun",78]]],
    [["Rohit",90], ["Swati",88]]
]



len(performance)

weekly_sales = [
    ["Chennai",[12000, 15000, 17000]],
    ["Delhi",[10000, 12000, 14000]],
    ["Mumbai",[15000, 18000, 20000]],
]

weekly_sales

x=[1,2,3,4]

x

x

x=[1,2,3]
y=[4,5,6]
x.extend(y)

x

x=[1,2,3,4]

x.insert(-1,"data")

x

x=[1,2,3,4]

x.pop(2)

x

x=[1,2,3,4]

x.remove(2)

x

x=[1,2,2,3,3,3,4,5]
x.count(2)



